import {
  ContributionContextEnum,
  ContributionDifficultyEnum,
  ContributionDurationEnum,
  ProjectRepository,
  ContributionStatusEnum,
  ContributionTypeEnum,
  ProjectDto,
} from "./repository";

export class InMemoryProjectRepository implements ProjectRepository {
  private projects: ProjectDto[] = [
    {
      id: "1",
      title: "Project 1",
      description: "Description 1",
      github_link: "https://example.com/projects/1",
      discord_link: "https://example.com/discord/1",
      website_link: "https://example.com/website/1",
      contributions: [
        {
          id: "1",
          title: "Contribution 1",
          description: "Description 1",
          status: ContributionStatusEnum.OPEN,
          github_link: "https://example.com/contributions/1",
          gate: 0,
          metadata: {
            context: ContributionContextEnum.ISOLATED,
            difficulty: ContributionDifficultyEnum.EASY,
            duration: ContributionDurationEnum.UNDER_A_DAY,
            technology: undefined,
            type: ContributionTypeEnum.FEATURE,
          },
        },
        {
          id: "6",
          title: "Contribution 6",
          description: "Description 6",
          status: ContributionStatusEnum.ASSIGNED,
          github_link: "https://example.com/contributions/6",
          gate: 0,
          metadata: {
            assignee: "0x123456789",
            github_username: "github-user-0x26",
            context: ContributionContextEnum.ISOLATED,
            difficulty: ContributionDifficultyEnum.EASY,
            duration: ContributionDurationEnum.UNDER_A_DAY,
            technology: undefined,
            type: ContributionTypeEnum.FEATURE,
          },
        },
        {
          id: "7",
          title: "Contribution 7",
          description: "Description 7",
          status: ContributionStatusEnum.OPEN,
          github_link: "https://example.com/contributions/7",
          gate: 10,
          metadata: {
            context: ContributionContextEnum.ISOLATED,
            difficulty: ContributionDifficultyEnum.EASY,
            duration: ContributionDurationEnum.UNDER_A_DAY,
            technology: undefined,
            type: ContributionTypeEnum.FEATURE,
          },
        },
      ],
      members: ["0x0abcdefabcdef"],
      logo: "https://app.onlydust.xyz/assets/onlydust-logo.5f8cc594.png",
    },
    {
      id: "2",
      title: "Project 2",
      description: "Description 2",
      github_link: "https://example.com/projects/2",
      contributions: [],
      members: [],
    },
    {
      id: "3",
      title: "Project 3",
      description: "Description 3",
      github_link: "https://example.com/projects/3",
      contributions: [
        {
          id: "2",
          title: "Contribution 2",
          description: "Description 2",
          status: ContributionStatusEnum.COMPLETED,
          github_link: "https://example.com/contributions/2",
          gate: 0,
          metadata: {
            assignee: "0x8888",
            github_username: "github-user-0x8888",
            context: ContributionContextEnum.COUPLED,
            difficulty: ContributionDifficultyEnum.INTERMEDIATE,
            duration: ContributionDurationEnum.FEW_DAYS,
            technology: "javascript",
            type: ContributionTypeEnum.FEATURE,
          },
        },
        {
          id: "3",
          title: "Contribution 3",
          description: "Description 3",
          status: ContributionStatusEnum.OPEN,
          github_link: "https://example.com/contributions/3",
          gate: 0,
          metadata: {
            context: ContributionContextEnum.COUPLED,
            difficulty: ContributionDifficultyEnum.EASY,
            duration: ContributionDurationEnum.UNDER_A_DAY,
            technology: "rust",
            type: ContributionTypeEnum.DOCUMENTATION,
          },
        },
        {
          id: "4",
          title: "Contribution 4",
          description: "Description 4",
          status: ContributionStatusEnum.OPEN,
          github_link: "https://example.com/contributions/4",
          gate: 0,
          metadata: {
            context: ContributionContextEnum.COUPLED,
            difficulty: ContributionDifficultyEnum.EASY,
            duration: ContributionDurationEnum.UNDER_A_DAY,
            technology: "rust",
            type: ContributionTypeEnum.DOCUMENTATION,
          },
        },
        {
          id: "5",
          title: "Contribution 5",
          description: "Description 5",
          status: ContributionStatusEnum.OPEN,
          github_link: "https://example.com/contributions/5",
          gate: 1000000000,
          metadata: {
            context: ContributionContextEnum.INTRICATED,
            difficulty: ContributionDifficultyEnum.HARD,
            duration: ContributionDurationEnum.WEEKS,
            technology: "rust",
            type: ContributionTypeEnum.REFACTOR,
          },
        },
        {
          id: "8",
          title: "Contribution 8",
          description: "Description 8",
          status: ContributionStatusEnum.ASSIGNED,
          github_link: "https://example.com/contributions/8",
          gate: 0,
          metadata: {
            assignee: "0x999",
            github_username: "github-user-0x1",
            context: ContributionContextEnum.ISOLATED,
            difficulty: ContributionDifficultyEnum.EASY,
            duration: ContributionDurationEnum.UNDER_A_DAY,
            technology: undefined,
            type: ContributionTypeEnum.FEATURE,
          },
        },
      ],
      members: [
        "0x123456789",
        "0x012c0407D341F351E000b894c3a0d226Bc971caEd123eF1abb9388f6AA02AED0",
        "0x123456789abcdef",
      ],
    },
  ];

  public async list(): Promise<ProjectDto[]> {
    return this.projects;
  }
}
