name: Build and deploy for production

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install yarn
        run: npm install -g yarn
      - run: yarn install --from-lockfile
      - name: Build project
        run: yarn build:prod
        env:
          MARKETPLACE_DATA_API_HOSTNAME: ${{ secrets.MARKETPLACE_DATA_API_HOSTNAME }}
          MARKETPLACE_SIGNUP_API_HOSTNAME: ${{ secrets.MARKETPLACE_SIGNUP_API_HOSTNAME }}
          MARKETPLACE_GITHUB_CLIENT_ID: ${{ secrets.MARKETPLACE_GITHUB_CLIENT_ID }}
          MARKETPLACE_GITHUB_REDIRECT_URI: ${{ secrets.MARKETPLACE_GITHUB_REDIRECT_URI }}
          MARKETPLACE_PROVIDER_NETWORK: ${{ secrets.MARKETPLACE_PROVIDER_NETWORK }}
          MARKETPLACE_REGISTRY_CONTRACT_ADDRESS: ${{ secrets.MARKETPLACE_REGISTRY_CONTRACT_ADDRESS }}
          MARKETPLACE_TYPEFORM_APPLY_URL: ${{ secrets.MARKETPLACE_TYPEFORM_APPLY_URL }}
          MARKETPLACE_TYPEFORM_SUBMIT_URL: ${{ secrets.MARKETPLACE_TYPEFORM_SUBMIT_URL }}
          MARKETPLACE_SENTRY_DSN: ${{ secrets.MARKETPLACE_SENTRY_DSN }}
          MARKETPLACE_SENTRY_ENVIRONMENT: ${{ secrets.MARKETPLACE_SENTRY_ENVIRONMENT }}
          MARKETPLACE_SENTRY_RELEASE: ${{ secrets.GITHUB_SHA }}
          MARKETPLACE_SENTRY_TRACES_SAMPLE_RATE: ${{ secrets.MARKETPLACE_SENTRY_TRACES_SAMPLE_RATE }}
          MARKETPLACE_SENTRY_AUTH_TOKEN: ${{ secrets.MARKETPLACE_SENTRY_AUTH_TOKEN }}
          MARKETPLACE_SENTRY_ORG: ${{ secrets.MARKETPLACE_SENTRY_ORG }}
          MARKETPLACE_SENTRY_PROJECT: ${{ secrets.MARKETPLACE_SENTRY_PROJECT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Copy files to the production frontend with the AWS CLI
        run: |
          aws s3 sync --delete dist s3://onlydust-marketplace-frontend
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E2CSPLZPZT8HV9 --paths "/*"
      - name: Uninstall yarn
        run: npm uninstall -g yarn
